[theme]
primaryColor = "#4A90E2"
backgroundColor = "#F0F2F6"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#262730"
font = "sans serif"

[server]
enableStaticServing = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200

[browser]
gatherUsageStats = false

[runner]
# Controls whether and how frequently the script gets automatically rerun when it's changed
magicEnabled = true
fastReruns = true
